import { baseApi } from "./base";

// Generated by https://quicktype.io

export interface Dict {
  name: string;
  id: number;
  value: string;
  code: string;
}

const DictApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    //获取所有字典
    getAllDict: builder.query<Dict[], void>({
      query: () => ({
        url: "/movieSysDict/dict",
        method: "GET",
      }),
    }),
  }),
});

export const { useLazyGetAllDictQuery } = DictApi;

export default DictApi;
