import { baseApi } from "./base";

// Generated by https://quicktype.io

export interface Movie {
  cover: string;
  director: string;
  evaluateNum: number;
  hotId: number;
  movieId: number;
  hotShortCommend: string;
  movieCountry: string;
  movieTime: string;
  preview: string;
  protagonist: string;
  rate: number;
  release: string;
  star: number;
  title: string;
  seemNum: number;
  comingData: string;
  type: string;
  synopsis: string;
}

// Generated by https://quicktype.io

export interface MovieSoon {
  comingData: string;
  cover: string;
  director: string;
  movieCountry: string;
  movieTime: string;
  preview: string;
  protagonist: string;
  seemNum: number;
  soonId: number;
  title: string;
  type: string;
} // Generated by https://quicktype.io

export interface HighRequest {
  current: number;
  size: number;
  input: Partial<{
    title: string;
    rate: string;
    director: string;
    status: number;
    type: string;
    protagonist: string;
  }>;
}
export interface PageResponse<T> {
  current: number;
  size: number;
  total: number;
  records: T[];
}

const MovieApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    //获取所有热映列表
    getAllHotMovie: builder.query<Movie[], void>({
      query: () => ({
        url: "/movieHotRelase/list",
        method: "GET",
      }),
    }),
    //获取所有待映列表
    getAllSoonMovie: builder.query<MovieSoon[], void>({
      query: () => ({
        url: "/movieSoon/list",
        method: "GET",
      }),
    }),
    //获取所有电影
    getAllMovie: builder.mutation<PageResponse<Movie>, HighRequest>({
      query: (data) => ({
        url: "/movieInfo/query",
        method: "POST",
        data: data,
      }),
    }),
    //获取社区电影
    getHighMovie: builder.mutation<PageResponse<Movie>, HighRequest>({
      query: (data) => ({
        url: "/movieInfo/page",
        method: "POST",
        data: data,
      }),
    }),
    //获取电影详情
    getMovieInfo: builder.query<Movie, number>({
      query: (id) => ({
        url: `/movieInfo/${id}`,
        method: "GET",
      }),
    }),
    //获取热映电影详情
    getMovieHotInfo: builder.query<Movie, number>({
      query: (id) => ({
        url: `/movieHotRelase/${id}`,
        method: "GET",
      }),
    }),
    //获取待映电影详情
    getMovieSoonInfo: builder.query<Movie, number>({
      query: (id) => ({
        url: `/movieSoon/${id}`,
        method: "GET",
      }),
    }),
  }),
});

export const {
  useGetAllHotMovieQuery,
  useLazyGetAllHotMovieQuery,
  useLazyGetAllSoonMovieQuery,
  useGetAllMovieMutation,
  useGetHighMovieMutation,
  useLazyGetMovieInfoQuery,
  useLazyGetMovieSoonInfoQuery,
  useLazyGetMovieHotInfoQuery,
} = MovieApi;

export default MovieApi;
