import { Input } from "@tarojs/components";
import { baseApi } from "./base";

// Generated by https://quicktype.io

export interface Movie {
  cover: string;
  director: string;
  evaluateNum: number;
  hotId: number;
  hotShortCommend: string;
  movieCountry: string;
  movieTime: string;
  preview: string;
  protagonist: string;
  rate: number;
  release: string;
  star: number;
  title: string;
  type: string;
}

// Generated by https://quicktype.io

export interface MovieSoon {
  comingData: string;
  cover: string;
  director: string;
  movieCountry: string;
  movieTime: string;
  preview: string;
  protagonist: string;
  seemNum: number;
  soonId: number;
  title: string;
  type: string;
} // Generated by https://quicktype.io

export interface MovieInfo {
  movieId: number;
  rate: string;
  title: string;
  cover: string;
  isNew: boolean;
}

export interface InfoRequst {
  current: number;
  size: number;
  input: {
    title?: string;
    rate?: string;
  };
}

export interface InfoResponse<T> {
  current: number;
  size: number;
  total: number;
  records: T[];
}

const MovieApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    //获取所有热映列表
    getAllHotMovie: builder.query<Movie[], void>({
      query: () => ({
        url: "/movieHotRelase/list",
        method: "GET",
      }),
    }),
    //获取所有待映列表
    getAllSoonMovie: builder.query<MovieSoon[], void>({
      query: () => ({
        url: "/movieSoon/list",
        method: "GET",
      }),
    }),
    getAllMovie: builder.mutation<InfoResponse<MovieInfo>, InfoRequst>({
      query: (data) => ({
        url: "/movieInfo/query",
        method: "POST",
        data: data,
      }),
    }),
  }),
});

export const {
  useGetAllHotMovieQuery,
  useLazyGetAllHotMovieQuery,
  useLazyGetAllSoonMovieQuery,
  useGetAllMovieMutation,
} = MovieApi;

export default MovieApi;
